#
# ________  ___  ___  ___  ________  ___  __    ________  ___       _______   _______   ________
#|\   __  \|\  \|\  \|\  \|\   ____\|\  \|\  \ |\   ____\|\  \     |\  ___ \ |\  ___ \ |\   __  \
#\ \  \|\  \ \  \\\  \ \  \ \  \___|\ \  \/  /|\ \  \___|\ \  \    \ \   __/|\ \   __/|\ \  \|\  \
# \ \  \\\  \ \  \\\  \ \  \ \  \    \ \   ___  \ \_____  \ \  \    \ \  \_|/_\ \  \_|/_\ \   ____\
#  \ \  \\\  \ \  \\\  \ \  \ \  \____\ \  \\ \  \|____|\  \ \  \____\ \  \_|\ \ \  \_|\ \ \  \___|
#   \ \_____  \ \_______\ \__\ \_______\ \__\\ \__\____\_\  \ \_______\ \_______\ \_______\ \__\
#    \|___| \__\|_______|\|__|\|_______|\|__| \|__|\_________\|_______|\|_______|\|_______|\|__|
#          \|__|                                  \|_________|
#
#
#Version 1.0.0
#
# mode: 1 使用玩家睡觉的百分比来跳过夜晚
# mode: 2 使用固定数量的玩家需要睡觉来跳过夜晚
mode: 2

# 玩家睡觉的百分比。仅当 mode 设置为 1 时有效。
sleep-percentage: 0.5

# 固定数量的玩家需要睡觉。仅当 mode 设置为 2 时有效。
fixed-amount: 3
